version: '3'

services:
  prosody:
    image: prosody/prosody:latest
    ports:
      - "5222:5222"
      - "5280:5280"
      - "5347:5347"
    environment:
      - PROSODY_ADMINS=admin@localhost
      - PROSODY_ENABLE_REGISTRATION=true
      - PROSODY_AUTHENTICATION=internal_plain
    volumes:
      - ./prosody-data:/var/lib/prosody
